language: generic 
sudo: required
services:
 - docker

before_install:
 - docker build -t shilajitgr/docker-react .

script:
 - docker run -e CI=true shilajitgr/docker-react npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "us-east-1" 
 app: "docker-react"
 env: "Dockerreact-env"
 bucket_name: "elasticbeanstalk-us-east-1-131287889761"
 bucket_path: "docker-react"
 on:
  branch: diff-base-img
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY
