language: generic 
sudo: required
services:
 - docker

before_install:
 - docker build -t shilajitgr/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true shilajitgr/docker-react npm run test -- --coverage
